### ISSUE TITLE
Is it absolutely necessary to add the hosts entry?

### ISSUE THREAD

**Issue by praveenpuglia** [dhavalpzala/Devstream-UI#30]
Because if yes, it obviously makes it absolutely painful to use the real app out there. I don't like toggling my hosts file settings again and again just to make the app work locally once and then have a look at the prod one.

**Comment by hashd** [comment]
It has to do with the way CAS works, CAS will only authorize certain domains.

**Comment by praveenpuglia** [comment]
So how does somebody, planning to contribute, make it work locally? 

When I do `npm run server` it's failing with the following. My assumptions is that it's due to hosts settings.

```
> devstream@0.0.1 server /Users/praveenp/code/github/Devstream-UI
> webpack-dev-server --output-public-path=/assets/ --content-base=public/ --hot --inline --open

[HPM] Proxy created: /github-api  ->  https://github.com
[HPM] Proxy rewrite rule created: "^/github-api" ~> ""
[HPM] Proxy created: /devstream-api  ->  http://192.168.2.67:9001
[HPM] Proxy rewrite rule created: "^/devstream-api" ~> ""
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 14.141.6.170:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/praveenp/.nvm/versions/node/v6.8.0/bin/node" "/Users/praveenp/.nvm/versions/node/v6.8.0/bin/npm" "run" "server"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! devstream@0.0.1 server: `webpack-dev-server --output-public-path=/assets/ --content-base=public/ --hot --inline --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devstream@0.0.1 server script 'webpack-dev-server --output-public-path=/assets/ --content-base=public/ --hot --inline --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the devstream package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --output-public-path=/assets/ --content-base=public/ --hot --inline --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs devstream
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls devstream
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/praveenp/code/github/Devstream-UI/npm-debug.log
```

This also means that no one can work just with the UI piece? No mock data?

**Comment by praveenpuglia** [comment]
At any case, if the DevStream service is an absolute must, let's mention that in the README.

**Comment by hashd** [comment]
I'll leave it to you as an exercise to debug the above issue, its a straight forward one
